apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-deployment
  name: jenkins-deployment
  namespace: jenkins-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom
            - name: TIME_ZONE
              value: -Dlogback.timezone=Asia/Bangkok
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: image-container
          name: jenkins-deployment
          volumeMounts:
            - mountPath: /home/
              name: jenkins-deployment-volume
      volumes:
        - configMap:
            defaultMode: 420
            name: jenkins-deployment-config
          name: jenkins-deployment-volume
