apiVersion: v1
data:
  application.properties: |
    spring.datasource.url=jdbc:oracle:thin:@exadev-scan.dev.dsl:1535:DSLCORD
    spring.datasource.username=dsladm
    spring.datasource.password=DSLADM#2019
    spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
    spring.datasource.hikari.maximum-pool-size=20
    spring.datasource.hikari.minimum-idle=2
    spring.datasource.hikari.leak-detection-threshold=0

    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always
    spring.mvc.date-format=dd/MM/yyyy HH:mm:ss
    server.port=9999
    
    # max file size
    spring.servlet.multipart.max-file-size=5MB
    # max request size
    spring.servlet.multipart.max-request-size=5MB

    logging.level.org.springframework=INFO
    logging.level.com.dsl=DEBUG
    spring.mvc.servlet.load-on-startup=1

    server.servlet.context-path=/jasperreport-service
    baseUrl=http://localhost:${server.port}/

kind: ConfigMap
metadata:
  name: jasperreport-service-config
  namespace: report
