pipeline {
    environment {
        jar = "jasperreport-service-0.0.1-SNAPSHOT.jar"
        registry = "registry91.dev.dsl:5000"
        imageName = "report/jasperreport-service"
        namespace = "report"
        deployment = "jasperreport-service"
        service = "jasperreport-service"
        nodePort = "30031"
        port = "9999"
        majorBuild = "0"
        minorBuild = "5"
        buildVersion = "$majorBuild.$minorBuild.${BUILD_NUMBER}"
        sshInfo = "dsladm@10.212.233.140"
        pathApp = "/home/dsladm/scripts/jenkins/report/jasperreport-service"
        buildEnv = "release"
        subProjectPath = "jasperreport-service"
    }
    agent any
    stages {
        stage('Build with Maven') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /data/mvn/.m2:/root/.m2'
                    reuseNode true
                }
            }

            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    mvn -version

                    pwd
                    cd $subProjectPath/libs/oracle_driver
                    mvn install:install-file -Dfile=ojdbc7-12.1.0.2.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.2 -Dpackaging=jar -DgeneratePom=true
                    cd ../../..

                    pwd
                    cd $subProjectPath
                    mvn clean
                    mvn install -X -Dmaven.test.skip=true

					pwd
                 '''
                 stash includes: "${env.subProjectPath}/target/${env.jar}", name: 'targetfiles'
            }
        }

        stage('Build Image') {
            steps {
                script {
                    unstash 'targetfiles'
                    sh "sed -i 's|jenkins-jar|${env.jar}|g' $WORKSPACE/$subProjectPath/deployment/resources/Dockerfile"
                    sh "sed -i 's|jenkins-subProjectPath|${env.subProjectPath}|g' $WORKSPACE/$subProjectPath/deployment/resources/Dockerfile"
                    a = docker.build("${env.registry}" + "/" + "${env.imageName}" + ":"+"${env.buildVersion}", "-f $subProjectPath/deployment/resources/Dockerfile .")
                    a.push()
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sshagent (credentials: ['sit-ssh-key-kube'])
                {
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/$subProjectPath/deployment/resources/namespace.yaml"
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/$subProjectPath/deployment/resources/deployment.yaml"
                    sh "sed -i 's|jenkins-deployment|$deployment|g' $WORKSPACE/$subProjectPath/deployment/resources/deployment.yaml"
                    sh "sed -i 's|image-container|$registry/$imageName:$buildVersion|g' $WORKSPACE/$subProjectPath/deployment/resources/deployment.yaml"
                    sh "sed -i 's|jenkins-namespace|$namespace|g' $WORKSPACE/$subProjectPath/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-deployment|$deployment|g' $WORKSPACE/$subProjectPath/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-service|$service|g' $WORKSPACE/$subProjectPath/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-port|$port|g' $WORKSPACE/$subProjectPath/deployment/resources/service.yaml"
                    sh "sed -i 's|jenkins-node-port|$nodePort|g' $WORKSPACE/$subProjectPath/deployment/resources/service.yaml"
                    sh '''
                        ssh -o StrictHostKeyChecking=no $sshInfo mkdir -p $pathApp
                        scp $WORKSPACE/$subProjectPath/deployment/resources/* $sshInfo:$pathApp
                        scp $WORKSPACE/$subProjectPath/deployment/$buildEnv/config-map.yaml $sshInfo:$pathApp
                        ssh -o StrictHostKeyChecking=no $sshInfo uname -a
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/namespace.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/config-map.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/deployment.yaml
                        ssh -o StrictHostKeyChecking=no $sshInfo /usr/bin/kubectl apply -f $pathApp/service.yaml
                    '''
                }
           	}
        }
    }
}